name: CD

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Deploying ${{ matrix.build_target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_target: [linux64]
        include:
          - build_target: linux64
            os: ubuntu-latest
            artifact_suffix: linux-x86_64
            target_arch: amd64
            target_os: linux
    env:
      PREFIX: ./${{ matrix.artifact_suffix }}
    steps:
      - name: Set up access
        uses: actions/checkout@v2
      - name: Setup up Nim
        uses: jiro4989/setup-nim-action@v2.2.2
      - name: Set up Linux deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libssh2-1-dev libssl-dev libbrotli-dev pkg-config make
      - name: Build
        run: make
      - name: Install
        run: make install
      - name: Package
        shell: bash
        run: |
          ls -la
          tar czvf cha-${{ matrix.artifact_suffix }}.tar.gz ${{ matrix.artifact_suffix }}/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: cha-${{ matrix.artifact_suffix }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
